<?php
define('CATEGORY_NONE', 0);
define('CATEGORY_TOPPING_SOURCE', 1);
define('PRODUCT_TOPPING_SOURCE', 0);

define('PRODUCT_IS_SHIP_ACTIVE', 1);
define('PRODUCT_IS_SHIP_INACTIVE', 0);
//group_option_product_type
define('GROUP_OPTION_PRODUCT_TYPE_SINGLE_CHOICE', 1);
define('GROUP_OPTION_PRODUCT_TYPE_MULTI_CHOICE', 2);
define('GROUP_OPTION_PRODUCT_TYPE_SHOW_SLIDE', 1);
define('GROUP_OPTION_PRODUCT_TYPE_SHOW_TAG', 2);
define('GROUP_OPTION_PRODUCT_TYPE_SHOW_CHECKBOX', 3);
